import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:flutter_secure_storage/flutter_secure_storage.dart';
import 'package:intl/intl.dart';
import 'api_service.dart';

void main() => runApp(const KatibaApp());

class KatibaApp extends StatelessWidget {
  const KatibaApp({super.key});
  @override Widget build(BuildContext context) => MaterialApp(
    debugShowCheckedModeBanner: false, title: 'Katiba VPN', locale: const Locale('ar'),
    theme: ThemeData(useMaterial3: true, fontFamily: 'sans', colorScheme: ColorScheme.fromSeed(seedColor: const Color(0xff7c3aed), brightness: Brightness.dark), scaffoldBackgroundColor: const Color(0xff0b1020)),
    home: const SessionGate(),
  );
}

class SessionGate extends StatefulWidget { const SessionGate({super.key}); @override State<SessionGate> createState()=>_SessionGateState(); }
class _SessionGateState extends State<SessionGate> {
  final store = const FlutterSecureStorage(); final api = ApiService(); Map<String,String>? headers;
  @override void initState(){super.initState(); _load();}
  Future<void> _load() async { final raw=await store.read(key:'session_headers'); if(raw!=null){try{headers=Map<String,String>.from(jsonDecode(raw));}catch(_){}} if(mounted)setState((){}); }
  @override Widget build(BuildContext context)=>headers==null?LoginPage(api:api,onLogin:(h)async{await store.write(key:'session_headers',value:jsonEncode(h));setState(()=>headers=h);},):HomePage(api:api,headers:headers!,onLogout:()async{await store.delete(key:'session_headers');setState(()=>headers=null);});
}

class LoginPage extends StatefulWidget { final ApiService api; final Future<void> Function(Map<String,String>) onLogin; const LoginPage({super.key,required this.api,required this.onLogin}); @override State<LoginPage> createState()=>_LoginPageState(); }
class _LoginPageState extends State<LoginPage>{ final phone=TextEditingController(), code=TextEditingController(); Map<String,String>? otpHeaders; bool sent=false,busy=false; String? error; String normalize(String x){x=x.trim();if(x.startsWith('01'))return '2$x';if(x.startsWith('+2'))return x.substring(1);return x.replaceAll(RegExp(r'[ +]'),'');}
 Future<void> send()async{if(phone.text.trim().isEmpty)return;setState(()=>busy=true);try{otpHeaders=widget.api.baseHeaders();await widget.api.sendCode(normalize(phone.text),otpHeaders!);setState(()=>sent=true);}catch(e){setState(()=>error=e.toString());}finally{setState(()=>busy=false);}}
 Future<void> verify()async{if(otpHeaders==null)return;setState(()=>busy=true);try{final h=await widget.api.verify(normalize(phone.text),code.text.trim(),otpHeaders!);await widget.onLogin(h);}catch(e){setState(()=>error=e.toString());}finally{if(mounted)setState(()=>busy=false);}}
 @override Widget build(BuildContext c)=>Scaffold(body: SafeArea(child: Center(child: SingleChildScrollView(padding:const EdgeInsets.all(24),child:ConstrainedBox(constraints:const BoxConstraints(maxWidth:460),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[const Icon(Icons.shield_rounded,size:82,color:Color(0xffa78bfa)),SizedBox(height:14),Text('KATIBA VPN',textAlign:TextAlign.center,style:TextStyle(fontSize:32,fontWeight:FontWeight.w900,letterSpacing:2)),SizedBox(height:8),Text('إدارة الرصيد والمهام والوحدات',textAlign:TextAlign.center,style:TextStyle(color:Colors.white60)),SizedBox(height:36),_Label('رقم الهاتف'),TextField(controller:phone,keyboardType:TextInputType.phone,decoration:_dec('مثال: 010xxxxxxxx',Icons.phone_android)),if(sent)...[const SizedBox(height:16),_Label('رمز التحقق'),TextField(controller:code,keyboardType:TextInputType.number,decoration:_dec('أدخل الرمز المرسل',Icons.lock_outline))],if(error!=null)...[const SizedBox(height:14),Text(error!,textAlign:TextAlign.center,style:const TextStyle(color:Colors.redAccent))],const SizedBox(height:24),FilledButton.icon(onPressed:busy?null:(sent?verify:send),icon:busy?const SizedBox(width:18,height:18,child:CircularProgressIndicator(strokeWidth:2)):Icon(sent?Icons.login:Icons.sms),label:Text(busy?'جاري التنفيذ...':sent?'تسجيل الدخول':'إرسال رمز التحقق'),style:FilledButton.styleFrom(padding:const EdgeInsets.symmetric(vertical:16))),if(sent)TextButton(onPressed:busy?null:()=>setState(()=>sent=false),child:const Text('تغيير الرقم'))]))))));
}
InputDecoration _dec(String hint,IconData icon)=>InputDecoration(hintText:hint,prefixIcon:Icon(icon),filled:true,fillColor:Colors.white.withOpacity(.07),border:OutlineInputBorder(borderRadius:BorderRadius.circular(16),borderSide:BorderSide.none));
class _Label extends StatelessWidget{final String text;const _Label(this.text);@override Widget build(BuildContext c)=>Padding(padding:const EdgeInsets.only(bottom:8),child:Text(text,style:const TextStyle(fontWeight:FontWeight.bold)));}

class HomePage extends StatefulWidget{final ApiService api;final Map<String,String> headers;final VoidCallback onLogout;const HomePage({super.key,required this.api,required this.headers,required this.onLogout});@override State<HomePage> createState()=>_HomePageState();}
class _HomePageState extends State<HomePage>{int tab=0;int balance=0;List<dynamic> history=[];List<PackageOption> options=[];bool loading=true;String status='';static const limit=2000;
 @override void initState(){super.initState();refresh();}
 Future<void> refresh()async{setState(()=>loading=true);try{balance=await widget.api.balance(widget.headers);history=await widget.api.history(widget.headers);final used=monthlyUnits(history);options=await widget.api.packages(widget.headers,balance,limit-used); }catch(e){status=e.toString();}finally{if(mounted)setState(()=>loading=false);}}
 int monthlyUnits(List<dynamic> rows){final now=DateTime.now();var total=0;for(final x in rows){if(x is! Map)continue;final ts=int.tryParse('${x['date']??0}')??0;if(ts==0)continue;final d=DateTime.fromMillisecondsSinceEpoch(ts);if(d.year!=now.year||d.month!=now.month||x['direction']!='DEBIT')continue;final s='${x['description']??''}';final m=RegExp(r'(\d+)\s*(?:وحدة|وحده|Units?|وحدات|EAND)',caseSensitive:false).firstMatch(s);if(m!=null)total+=int.parse(m.group(1)!);}return total;}
 Future<void> collect()async{setState(()=>loading=true);try{final before=await widget.api.balance(widget.headers);final result=await widget.api.collectAll(widget.headers,(s)=>setState(()=>status=s));final after=await widget.api.balance(widget.headers);status='اكتملت ${result.completed} مهمة — +${after-before} كوينز';}catch(e){status=e.toString();}finally{await refresh();}}
 Future<void> redeem(PackageOption p)async{final ok=await showDialog<bool>(context:context,builder:(_)=>AlertDialog(title:const Text('تأكيد السحب'),content:Text('سحب ${p.units} وحدة مقابل ${p.cost} كوينز؟'),actions:[TextButton(onPressed:()=>Navigator.pop(context,false),child:const Text('إلغاء')),FilledButton(onPressed:()=>Navigator.pop(context,true),child:const Text('تأكيد'))]));if(ok!=true)return;setState(()=>loading=true);try{await widget.api.redeem(widget.headers,p);status='تم السحب بنجاح: ${p.units} وحدة';}catch(e){status=e.toString();}finally{await refresh();}}
 @override Widget build(BuildContext c)=>Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:AppBar(title:const Text('KATIBA VPN',style:TextStyle(fontWeight:FontWeight.w900)),actions:[IconButton(onPressed:refresh,icon:const Icon(Icons.refresh)),IconButton(onPressed:widget.onLogout,icon:const Icon(Icons.logout))]),body:loading?const Center(child:CircularProgressIndicator()):IndexedStack(index:tab,children:[dashboard(),missions(),historyPage(),redeemPage()]),bottomNavigationBar:NavigationBar(selectedIndex:tab,onDestinationSelected:(i)=>setState(()=>tab=i),destinations:const[NavigationDestination(icon:Icon(Icons.dashboard_outlined),selectedIcon:Icon(Icons.dashboard),label:'الرئيسية'),NavigationDestination(icon:Icon(Icons.bolt_outlined),selectedIcon:Icon(Icons.bolt),label:'المهام'),NavigationDestination(icon:Icon(Icons.receipt_long_outlined),selectedIcon:Icon(Icons.receipt_long),label:'السجل'),NavigationDestination(icon:Icon(Icons.card_giftcard_outlined),selectedIcon:Icon(Icons.card_giftcard),label:'السحب')],)));
 Widget dashboard(){final used=monthlyUnits(history),remaining=(limit-used).clamp(0,limit),percent=used/limit;return ListView(padding:const EdgeInsets.all(18),children:[_hero(balance),const SizedBox(height:16),if(status.isNotEmpty)_status(status),Row(children:[Expanded(child:_metric('المستخدم هذا الشهر','$used','وحدة',Colors.orange)),const SizedBox(width:12),Expanded(child:_metric('المتبقي','$remaining','وحدة',Colors.green))]),const SizedBox(height:16),Card(child:Padding(padding:const EdgeInsets.all(18),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('تقدم الحد الشهري',style:TextStyle(fontWeight:FontWeight.bold)),const SizedBox(height:12),LinearProgressIndicator(value:percent.clamp(0.0,1.0).toDouble(),minHeight:10,borderRadius:BorderRadius.circular(8),color:percent>.8?Colors.orange:Colors.green),const SizedBox(height:8),Text('${(percent*100).toStringAsFixed(1)}% من $limit وحدة')]))),const SizedBox(height:18),FilledButton.icon(onPressed:collect,icon:const Icon(Icons.bolt),label:const Text('جمع المهام المتاحة'),style:FilledButton.styleFrom(padding:const EdgeInsets.all(16))),]);}
 Widget _hero(int b)=>Container(padding:const EdgeInsets.all(22),decoration:BoxDecoration(gradient:const LinearGradient(colors:[Color(0xff5b21b6),Color(0xff7c3aed)]),borderRadius:BorderRadius.circular(24)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('رصيدك الحالي',style:TextStyle(color:Colors.white70)),const SizedBox(height:8),Text('${NumberFormat('#,###').format(b)} كوينز',style:const TextStyle(fontSize:30,fontWeight:FontWeight.w900)),const SizedBox(height:12),Text(status.isEmpty?'كل بياناتك محدثة وآمنة':status,style:const TextStyle(color:Colors.white70))]));
 Widget _metric(String a,String b,String c,Color color)=>Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Icon(Icons.circle,color:color,size:14),const SizedBox(height:10),Text(a,style:const TextStyle(color:Colors.white60)),Text(b,style:TextStyle(fontSize:24,fontWeight:FontWeight.bold,color:color)),Text(c,style:const TextStyle(color:Colors.white60))])));
 Widget _status(String s)=>Padding(padding:const EdgeInsets.only(bottom:12),child:Card(color:Colors.deepPurple.withOpacity(.35),child:Padding(padding:const EdgeInsets.all(14),child:Text(s))));
 Widget missions()=>ListView(padding:const EdgeInsets.all(18),children:[_sectionTitle('جمع النقاط','تنفيذ المهام غير المكتملة'),FilledButton.icon(onPressed:collect,icon:const Icon(Icons.play_arrow),label:const Text('بدء جمع المهام')),if(status.isNotEmpty)Padding(padding:const EdgeInsets.only(top:16),child:_status(status))]);
 Widget historyPage()=>ListView(padding:const EdgeInsets.all(18),children:[_sectionTitle('سجل المعاملات','الوحدات المسحوبة خلال الشهر'),Card(child:Padding(padding:const EdgeInsets.all(16),child:Text('المسحوب هذا الشهر: ${monthlyUnits(history)} من $limit وحدة',style:const TextStyle(fontSize:18,fontWeight:FontWeight.bold)))),const SizedBox(height:12),...history.take(30).map((x)=>Card(child:ListTile(leading:Icon(x['direction']=='DEBIT'?Icons.arrow_upward:Icons.arrow_downward,color:x['direction']=='DEBIT'?Colors.redAccent:Colors.green),title:Text('${x['description']??'معاملة'}'),subtitle:Text(x['date']==null?'':DateFormat('yyyy/MM/dd').format(DateTime.fromMillisecondsSinceEpoch(int.tryParse('${x['date']}')??0))),trailing:Text('${x['amount']??''}'))))]);
 Widget redeemPage()=>ListView(padding:const EdgeInsets.all(18),children:[_sectionTitle('السحب المتاح','اختر باقة مناسبة لرصيدك'),if(options.isEmpty)const Card(child:Padding(padding:EdgeInsets.all(18),child:Text('لا توجد باقات متاحة حاليًا أو الرصيد غير كافٍ.'))) else ...options.map((p)=>Card(child:ListTile(leading:const Icon(Icons.card_giftcard,color:Colors.amber),title:Text('${p.units} وحدة',style:const TextStyle(fontWeight:FontWeight.bold)),subtitle:Text('${p.cost} كوينز'),trailing:FilledButton(onPressed:()=>redeem(p),child:const Text('سحب'))))]));
 Widget _sectionTitle(String a,String b)=>Padding(padding:const EdgeInsets.only(bottom:16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(a,style:const TextStyle(fontSize:26,fontWeight:FontWeight.w900)),Text(b,style:const TextStyle(color:Colors.white60))]));
}
